[package]
name = "twizsec"
version = "0.1.0"
edition = "2021"


[dependencies]
bitflags = "2.4.1"
getrandom = "0.2.15"
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }
# the only crate thats not already in the twiz repo
rand = { version = "0.8.5", default-features = false }
sha2 = { version = "0.10.8", default-features = false, features = [
    "force-soft",
] }

[dev-dependencies]
hex-literal = { version = "0.4.1", default-features = false }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "capability_ops"
harness = false
